"""Rows for checking whether a model learned the re-admitted attributes at all.

    uv run python scripts/build_readmitted_probe.py

v0.4 trains on five retired attributes that mistral wrote. If its held-out numbers do
not move, the first question is whether it learned those five in the first place, and
its own validation split cannot say: the attributes were forced onto training
documents only, so no validation row carries them.

The second smoke corpus can. It was generated by qwen3 while the ten were still in the
catalogue, verified by qwen3, and never merged into any training set. Its
verifier-confirmed pairs for the five make a small out-of-distribution probe -- written
by a *different* generator from the one v0.4 learned them from.

One asymmetry to read the result with: v0.1 trained on qwen3-written
`implies_pressure_from_others` (it was a Day 2 attribute), so on that one attribute
v0.1 is scored on its own generator's writing.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from sokudan.data import intent_attributes as ia

YES, UNKNOWN = "はい", "判断できない"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", default="data/smoke2_v4.jsonl")
    parser.add_argument("--out", default="data/v5/readmitted_probe.jsonl")
    args = parser.parse_args()

    rows, counts = [], Counter()
    for line in Path(args.corpus).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        document = json.loads(line)
        verdicts = document.get("verdicts") or {}
        for attribute_id, gold in document["intent_labels"].items():
            if attribute_id not in ia.READMITTED:
                continue
            answer = verdicts.get(attribute_id)
            if answer is None or answer == UNKNOWN or (answer == YES) != bool(gold):
                continue
            attribute = ia.BY_ID[attribute_id]
            question = attribute.question(0)
            rows.append({
                "doc_id": f"smoke2-{document['doc_id']}", "domain": document["domain"],
                "attribute": attribute_id, "kind": "bool", "source": "intent",
                "tier": attribute.tier, "negation": False, "variant": 0,
                "state": document["state"],
                "question": question.model_dump(mode="json"),
                "label": int(gold), "label_text": YES if gold else "いいえ",
                "n_options": 2,
            })
            counts[(attribute_id, int(gold))] += 1

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows),
                   encoding="utf-8")
    print(f"{len(rows)} rows -> {out}")
    for attribute_id in sorted(ia.READMITTED):
        positives, negatives = counts[(attribute_id, 1)], counts[(attribute_id, 0)]
        print(f"  {attribute_id:32s} +{positives:3d} / -{negatives:3d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
